"""create_user_taste_profile

Revision ID: fe0e6862dc51
Revises: a796a353799e
Create Date: 2026-07-31 17:31:01.936766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0e6862dc51'
down_revision: Union[str, Sequence[str], None] = 'a796a353799e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taste_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('spice_preference', sa.Float(), nullable=True),
    sa.Column('sweetness_preference', sa.Float(), nullable=True),
    sa.Column('creaminess_preference', sa.Float(), nullable=True),
    sa.Column('tanginess_preference', sa.Float(), nullable=True),
    sa.Column('smokiness_preference', sa.Float(), nullable=True),
    sa.Column('crunch_preference', sa.Float(), nullable=True),
    sa.Column('adventure_level', sa.Float(), nullable=True),
    sa.Column('portion_preference', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taste_profiles_user_id'), 'taste_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taste_profiles_user_id'), table_name='taste_profiles')
    op.drop_table('taste_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
